---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fluxcd.io/automated: "true"
    foo.io/bar: foobar
  name: podinfo
  namespace: demo
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: podinfod
      $setElementOrder/initContainers:
      - name: init
      containers:
      - image: juanlee/podinfo:v0.1.4
        name: podinfod
      initContainers:
      - image: alpine:3.8
        name: init
